name: Build Docker image and tagging
description:  Reusable action to build & tag a Docker image

inputs:
  aws_ecr_repo_name:
    description: The name of ECR repo
    required: true
  tag:
    description: The tag for the Docker image.
    required: true

runs:
  using: composite
  steps:
    - name: Build docker image
      run: |
        sudo chmod 777 /var/run/docker.sock
        docker build -t 774305578623.dkr.ecr.ap-southeast-1.amazonaws.com/${{inputs.aws_ecr_repo_name}}:{{inputs.tag}} . --no-cache
